# Autogenerated wrapper script for GALAHAD_jll for aarch64-apple-darwin-libgfortran5
export libgalahad, libgalahad_c, libgalahad_hsl

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("GALAHAD")
JLLWrappers.@declare_library_product(libgalahad, "@rpath/libgalahad.dylib")
JLLWrappers.@declare_library_product(libgalahad_c, "@rpath/libgalahad_c.dylib")
JLLWrappers.@declare_library_product(libgalahad_hsl, "@rpath/libgalahad_hsl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgalahad,
        "lib/libgalahad.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgalahad_c,
        "lib/libgalahad_c.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgalahad_hsl,
        "lib/libgalahad_hsl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
