# Autogenerated wrapper script for GALAHAD_jll for x86_64-linux-gnu-libgfortran5
export libgalahad, libgalahad_c, libgalahad_hsl

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("GALAHAD")
JLLWrappers.@declare_library_product(libgalahad, "libgalahad.so")
JLLWrappers.@declare_library_product(libgalahad_c, "libgalahad_c.so")
JLLWrappers.@declare_library_product(libgalahad_hsl, "libgalahad_hsl.so")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgalahad,
        "lib/libgalahad.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgalahad_c,
        "lib/libgalahad_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgalahad_hsl,
        "lib/libgalahad_hsl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
