# Autogenerated wrapper script for GALAHAD_jll for x86_64-w64-mingw32-libgfortran5
export libgalahad, libgalahad_c, libgalahad_hsl

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("GALAHAD")
JLLWrappers.@declare_library_product(libgalahad, "libgalahad.dll")
JLLWrappers.@declare_library_product(libgalahad_c, "libgalahad_c.dll")
JLLWrappers.@declare_library_product(libgalahad_hsl, "libgalahad_hsl.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgalahad,
        "bin\\libgalahad.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgalahad_c,
        "bin\\libgalahad_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgalahad_hsl,
        "bin\\libgalahad_hsl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
